config/routes.rb
Rails.application.routes.draw do
  resources :candies
  resources :questions
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'

  namespace :admin do
    root to: 'home#index'
    # ... authenticated admin routes ...
    constraints Rodauth::Rails.authenticated(:admin) do
      get '/dashboard/', to: 'home#dashboard', as: 'dashboard'
    end
  end

  # ... authenticated routes ...
  constraints Rodauth::Rails.authenticated do

    resources :profiles

    post '/profiles/:id/follow', to: 'profiles#follow_profile', as: 'follow_profile'
    post '/profiles/:id/unfollow', to: 'profiles#unfollow_profile', as: 'unfollow_profile'
    post '/profiles/:id/blocking', to: 'profiles#blocking_profile', as: 'blocking_profile'
    post '/profiles/:id/unblocking', to: 'profiles#unblocking_profile', as: 'unblocking_profile'
    post '/profiles/:id/accept', to: 'profiles#accept_following', as: 'accept_following'
    post '/profiles/:id/decline', to: 'profiles#decline_following', as: 'decline_following'
    post '/profiles/:id/cancel', to: 'profiles#cancel_following', as: 'cancel_following'

    resources :questions do
      put 'add_to_readlist', to: 'questions#add_to_readlist'
      put 'remove_to_readlist', to: 'questions#remove_to_readlist'
      put 'bookmark', to: 'questions#toggle_to_bookmark'
      patch 'update_tags', to: 'questions#update_tags'

      put 'awesome_question', to: 'questions#add_awesome'
      put 'perfect_question', to: 'questions#add_perfect'
      put 'nice_question', to: 'questions#add_nice'
      put 'wrong_question', to: 'questions#add_wrong'
      put 'bad_question', to: 'questions#add_bad'
    end
    
    resources :candies do
      put 'author', to: 'candies#see_the_author'
      put 'bookmark', to: 'candies#toggle_to_bookmark'
      put 'like', to: 'candies#toggle_to_like'
      put 'boost', to: 'candies#toggle_to_boost'
      put 'view', to: 'candies#toggle_to_view'
    end
  end

end

app/models/question.rb
class Question < ApplicationRecord
  attribute :uuid, MySQLBinUUID::Type.new
  before_create { self.uuid = ApplicationRecord.generate_uuid }
  after_create :create_slug
  before_update :update_slug
  belongs_to :question, class_name: "Question", optional: true
  belongs_to :account

  acts_as_taggable_on :tags
  acts_as_votable cacheable_strategy: :update_columns

  is_impressionable :counter_cache => true, :column_name => :views_count, :unique => :session_hash


  scope :desc, -> { order(created_at: :desc) }

  def to_param
    slug
  end 

  private

  def create_slug
    update_slug
    save!
  end

  def update_slug
    self.slug = [title&.parameterize, uuid].compact.join("-")
  end


end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action -> { rodauth.require_authentication }, except: %i[index show]
  before_action :user_authenticate
  before_action :set_question_by_slug, only: %i[update show edit destroy]
  before_action :find_question_for_vote,
                only: %i[toggle_to_bookmark add_to_readlist remove_to_readlist add_awesome add_perfect add_nice add_wrong add_bad
                get_global_appreciation_value get_appreciation]
  after_action :set_tags, only: %i[create]
  after_action :give_new_slug, only: %i[update]
  after_action :increment_question_counter, only: %i[create]
  after_action :decrement_question_counter, only: %i[destroy]

  ActsAsTaggableOn.remove_unused_tags = true
  ActsAsTaggableOn.force_lowercase = true
  # ActsAsTaggableOn.tags_table = 'tag_list'
  # ActsAsTaggableOn.taggings_table = 'tag_list'

  impressionist actions: [:show],
                unique: %i[action_name session_hash user_id impressionable_type impressionable_id ip_address]
  impressionist actions: [:index], unique: %i[impressionable_type impressionable_id session_hash ip_address]

  def pundit_user
    current_account
  end

  # GET /questions or /questions.json
  def index
    @questions = Question.includes(account: :profile)
    # @questions = Question.includes(account: :profile).where(is_private: false)
  end

  # GET /questions/1 or /questions/1.json
  def show
    @profile = Profile.find_by(profileable_id: @question.account_id)
    impressionist(@question, "visionnage de la question : #{@question.title}")
  end

  # add or remove the question to the bookmark of the user
  def toggle_to_bookmark
    if current_account.voted_up_on? @question, vote_scope: :bookmark
      @question.unvote_by current_account, vote_scope: :bookmark
    else
      @question.upvote_from current_account, vote_scope: :bookmark
    end
    respond_to do |format|
      format.html { redirect_to @question }
    end
  end

  # add appreciation to the question
  def add_awesome
    if (current_account.voted_up_on? @question, vote_scope: :appreciation) && (current_account.vote_weight_on(@question, vote_scope: :appreciation) === 3)
      remove_appreciation
      decrement_likes_counter(@question)
    else
      if current_account.voted_up_on? @question, vote_scope: :appreciation
        decrement_likes_counter(@question)
      end
      @question.upvote_by current_account, vote_scope: :appreciation, vote_weight: 3
      increment_likes_counter(@question)
    end
    respond_to do |format|
      format.html { redirect_to @question }
    end
  end

  def add_perfect
    if (current_account.voted_up_on? @question, vote_scope: :appreciation) && (current_account.vote_weight_on(@question, vote_scope: :appreciation) === 2)
      remove_appreciation
      decrement_likes_counter(@question)
    else
      if current_account.voted_up_on? @question, vote_scope: :appreciation
        decrement_likes_counter(@question)
      end
      @question.upvote_by current_account, vote_scope: :appreciation, vote_weight: 2
      increment_likes_counter(@question)
    end
    respond_to do |format|
      format.html { redirect_to @question }
    end
  end

  def add_nice
    if (current_account.voted_up_on? @question, vote_scope: :appreciation) && (current_account.vote_weight_on(@question, vote_scope: :appreciation) === 1)
      remove_appreciation
      decrement_likes_counter(@question)
    else
      if current_account.voted_up_on? @question, vote_scope: :appreciation
        decrement_likes_counter(@question)
      end
      @question.upvote_by current_account, vote_scope: :appreciation, vote_weight: 1
      increment_likes_counter(@question)
    end
    respond_to do |format|
      format.html { redirect_to @question }
    end

  end

  def add_wrong
    if current_account.voted_up_on? @question, vote_scope: :appreciation
      decrement_likes_counter(@question)
    end
    if (current_account.voted_down_on? @question, vote_scope: :appreciation) && (current_account.vote_weight_on(@question, vote_scope: :appreciation) === 1)
      remove_appreciation
    else
      @question.downvote_by current_account, vote_scope: :appreciation, vote_weight: 1
    end
    respond_to do |format|
      format.html { redirect_to @question }
    end
  end

  def add_bad
    if current_account.voted_up_on? @question, vote_scope: :appreciation
      decrement_likes_counter(@question)
    end
    if (current_account.voted_down_on? @question, vote_scope: :appreciation) && (current_account.vote_weight_on(@question, vote_scope: :appreciation) === 2)
      remove_appreciation
    else
      @question.downvote_by current_account, vote_scope: :appreciation, vote_weight: 2
    end
    respond_to do |format|
      format.html { redirect_to @question }
    end
  end

  # to verify if user has give an appreciation to the question
  def has_appreciate
    get_appreciation? nil
  end

  # get the global appreciation value of @question
  def get_global_appreciation_value
    upvote_global_value = (@question.get_upvotes(vote_scope: :appr_awesome).sum(:vote_weight)).to_i + (@question.get_upvotes(vote_scope: :appr_perfect).sum(:vote_weight)).to_i +  (@question.get_upvotes(vote_scope: :appr_nice).sum(:vote_weight)).to_i

    downvote_global_value = (@question.get_downvotes(vote_scope: :appr_wrong).sum(:vote_weight)).to_i - (@question.get_downvotes(vote_scope: :appr_bad).sum(:vote_weight)).to_i

    upvote_global_value - downvote_global_value
  end

  # add the question to a readlater list of the user
  def add_to_readlist
    if current_account.voted_for? @question, vote_scope: :readlist
      if current_account.voted_down_on? @question, vote_scope: :readlist
        @question.upvote_from current_account, vote_scope: :readlist
      else
        @question.downvote_from current_account, vote_scope: :readlist
      end
    else
      @question.downvote_from current_account, vote_scope: :readlist
    end
    respond_to do |format|
      format.html { redirect_to @question }
      # format.turbo_stream
    end
  end

  # remove the question to a readlater list of the user
  def remove_to_readlist
    if current_account.voted_for? @question, vote_scope: :readlist
      @question.unvote_by current_account, vote_scope: :readlist
    end
    respond_to do |format|
      format.html { redirect_to @question }
      # format.turbo_stream
    end
  end


  # GET /questions/new
  def new
    @question = Question.new
  end

  # POST /questions or /questions.json
  def create
    @question = current_account.questions.build(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
    authorize @question
  end

  # PATCH/PUT /questions/1 or /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question }
        format.turbo_stream
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def update_tags
    @question =Question.find_by(slug: params[:question_id])
    respond_to do |format|
      if @question.update(question_params_without_tags)
        @question[:tags] = @question.tag_list.join(', ')
        @question.save!
        format.html { redirect_to @question }
        format.turbo_stream
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1 or /questions/1.json
  def destroy
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
    end
  end

  private

  require 'json'

  def add_bookmark_list
    current_account.questions_count += 1
    current_account.save!
  end

  def remove_bookmark_list(question, profile)
    bookmark_list = JSON.parse(profile.bookmark_list)
    id_question = question.id
    if bookmark_list.include? id_question
      profile.bookmark_list
      current_account.save!
    end
  end

  def increment_question_counter
    current_account.questions_count += 1
    current_account.activity_rate += 0.1
    current_account.save!
  end

  def decrement_question_counter
    current_account.questions_count -= 1
    current_account.activity_rate -= 0.1
    current_account.save!
  end

  def increment_likes_counter(item)
    current_account.activity_rate += 0.007
    current_account.save!
    item.likes_count += 1
    item.save!
  end

  def decrement_likes_counter(item)
    current_account.activity_rate -= 0.007
    current_account.save!
    item.likes_count -= 1
    item.save!
  end

  def set_tags
    @question[:tags] = @question.tag_list.join(', ')
    @question.save!
  end

  # remove all appreciation by the current account to the question @question
  def remove_appreciation
    if current_account.voted_for? @question, vote_scope: :appreciation
      @question.unvote_by current_account, vote_scope: :appreciation
    end
  end

  # get the word to precise the appreciation [ awesome, perfect, nice, wrong, bad ]
  def get_appreciation
    if (current_account.voted_up_on? @question, vote_scope: :appreciation) && (current_account.vote_weight_on(@question, vote_scope: :appreciation) === 3)
      'awesome'
    end
    if (current_account.voted_up_on? @question, vote_scope: :appreciation) && (current_account.vote_weight_on(@question, vote_scope: :appreciation) === 2)
      'perfect'
    end
    if (current_account.voted_up_on? @question, vote_scope: :appreciation) && (current_account.vote_weight_on(@question, vote_scope: :appreciation) === 1)
      'nice'
    end
    if (current_account.voted_down_on? @question, vote_scope: :appreciation) && (current_account.vote_weight_on(@question, vote_scope: :appreciation) === 1)
      'wrong'
    end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_bookmark.html.erb
<% if rodauth.logged_in? %>
  <style>
  .bookmark {
    background-color:transparent;
    border:none
  }
  @media (prefers-color-scheme: light) {
    .bookmark:hover {
      background-color:#EFEFEF;
      border-radius:3px;
    }
  }

  @media (prefers-color-scheme: dark) {
    .bookmark:hover {
      background-color:#444;
      border-radius:3px;
    }
  }
  </style>
  <%= button_to question_bookmark_url(@question), class: "bookmark", method: :put do %>
    <div style="display:flex; align-items:center;">
      <% if current_account&.voted_for? @question, vote_scope: :bookmark %>
        <svg width="24" height="24" viewBox="0 0 32 32"><path fill="#FCD53F" d="m18.7 4.627l2.247 4.31a2.27 2.27 0 0 0 1.686 1.189l4.746.65c2.538.35 3.522 3.479 1.645 5.219l-3.25 2.999a2.225 2.225 0 0 0-.683 2.04l.793 4.398c.441 2.45-2.108 4.36-4.345 3.24l-4.536-2.25a2.282 2.282 0 0 0-2.006 0l-4.536 2.25c-2.238 1.11-4.786-.79-4.345-3.24l.793-4.399c.14-.75-.12-1.52-.682-2.04l-3.251-2.998c-1.877-1.73-.893-4.87 1.645-5.22l4.746-.65a2.23 2.23 0 0 0 1.686-1.189l2.248-4.309c1.144-2.17 4.264-2.17 5.398 0Z"/></svg>
      <% else %>
        <svg width="24" height="24" viewBox="0 0 32 32"><path fill="#999" d="m18.7 4.627l2.247 4.31a2.27 2.27 0 0 0 1.686 1.189l4.746.65c2.538.35 3.522 3.479 1.645 5.219l-3.25 2.999a2.225 2.225 0 0 0-.683 2.04l.793 4.398c.441 2.45-2.108 4.36-4.345 3.24l-4.536-2.25a2.282 2.282 0 0 0-2.006 0l-4.536 2.25c-2.238 1.11-4.786-.79-4.345-3.24l.793-4.399c.14-.75-.12-1.52-.682-2.04l-3.251-2.998c-1.877-1.73-.893-4.87 1.645-5.22l4.746-.65a2.23 2.23 0 0 0 1.686-1.189l2.248-4.309c1.144-2.17 4.264-2.17 5.398 0Z"/></svg>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/questions/_form.html.erb
<%= form_with(model: question) do |form| %>
  
  <div data-controller="select-tag" >
    <%= form.label :tag_list, style: "display: block" %>
    <%= form.text_field :tag_list, data: {select_tag_target: "select"} %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, placeholder: "sans titre" %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit "Enregistrer la question", class: "btn btn--primary" %>
  </div>
<% end %>

app/views/questions/_index_question.html.erb
<% if !rodauth.logged_in? || !current_account.blocked_by?(@question.account)  #(current_account === @question.account && @question.is_private?) || !@question.is_private?  %>
<% #current_account.is_premium %>
  <div style="height:20px"></div>
  <div class="">
    <div class="navbar__name" style="display:flex; align-items:center; justify-content:start">
      <div style=" display:flex; align-items:center;  justify-content: center;">
        <% if @question.account.profile.avatar.attached? %>
          <div class="picture_author">
            <%= image_tag(@question.account.profile.avatar_profile, style: "object-fit: cover; object-position: center;width:100%; height:100%; border-radius:100%", size:"27px") %>
          </div>
        <% else %>
          <div class="initial_author" style="background-color:<%= @question.account.profile.color %>; height:27px; width:27px;">
            <p style="font-size:9px">
              <%= @question.account.profile.get_initial_profile %>
            </p>
          </div>
        <% end %>
      </div>
      <p>
      <%= link_to (!@question.account.profile.lastname.nil? || !@question.account.profile.firstname.nil?) ? @question.account.profile.lastname.capitalize : @question.account.profile.username.capitalize , profile_url(@question.account.profile), class:"name_author" %>
      </p> 
      <p>
      <%= link_to " @#{@question.account.profile.username.downcase}" , profile_url(@question.account.profile), class:"username_author" %>
      </p>  
    </div>
  </div>
  <h2 class="question">
    <% if (current_account === @question.account && @question.is_private?) ||  !@question.is_private? %>
      <%= link_to @question.title, @question, class:"question__title" %>
    <% else %>
      <span class="question__title">
        <%= @question.title %>
      </span>
    <% end %>
    <% if @question.is_private? %>
      <svg xmlns="http://www.w3.org/2000/svg" width="17" height="17" viewBox="0 0 16 16" style="margin:auto 3px"><path fill="#FC0" d="M7.657 6.247c.11-.33.576-.33.686 0l.645 1.937a2.89 2.89 0 0 0 1.829 1.828l1.936.645c.33.11.33.576 0 .686l-1.937.645a2.89 2.89 0 0 0-1.828 1.829l-.645 1.936a.361.361 0 0 1-.686 0l-.645-1.937a2.89 2.89 0 0 0-1.828-1.828l-1.937-.645a.361.361 0 0 1 0-.686l1.937-.645a2.89 2.89 0 0 0 1.828-1.828l.645-1.937zM3.794 1.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387A1.734 1.734 0 0 0 4.593 5.69l-.387 1.162a.217.217 0 0 1-.412 0L3.407 5.69A1.734 1.734 0 0 0 2.31 4.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387A1.734 1.734 0 0 0 3.407 2.31l.387-1.162zM10.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732L9.1 2.137a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L10.863.1z"/></svg>
    <% end %>
  </h2>
  <div style="height:5px"></div>
  <%= render "taglist", as: :question %>
  <div style="display:flex; align-items:center">
    <%= render "bookmark", as: :question %>
    <div style="width:10px; height:10px"></div>
    <%#= render "readlist", as: :question %>
    <div style="width:10px; height:10px"></div>
    <%= render "view_question", as: :question %>
    <div style="width:20px; height:10px"></div>
    <p style="letter-spacing:0.1; font-size:11px; font-weight:600; color:#AAA">
      <%= @question.likes_count %>&nbsp;J'aime
    </p>
  </div>
<% end %>

app/views/questions/_question.html.erb
<style>
  .switch {
    position: relative;
    display: inline-block;
    width: 60px;
    height: 32px;
  }

  .switch input { 
    opacity: 0;
    width: 0;
    height: 0;
  }

  .slider {
    position: absolute;
    cursor: pointer;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background-color: #ccc;
    -webkit-transition: .4s;
    transition: .4s;
  }

  .slider:before {
    position: absolute;
    content: "";
    height: 24px;
    width: 24px;
    left: 4px;
    bottom: 4px;
    background-color: white;
    -webkit-transition: .4s;
    transition: .4s;
  }

  input:checked + .slider {
    background-color: <%= current_account.profile.color %>;
  }

  input:focus + .slider {
    box-shadow: 0 0 1px <%= current_account.profile.color %>;
  }

  input:checked + .slider:before {
    -webkit-transform: translateX(28px);
    -ms-transform: translateX(28px);
    transform: translateX(28px);
  }

  /* Rounded sliders */
  .slider.round {
    border-radius: 34px;
  }

  .slider.round:before {
    border-radius: 50%;
  }
</style>
<div class="container">
  <div style="width:100%; height:50px">
  </div>

  <div id="<%= dom_id question %>"> 
    <div style="display:flex; align-items:center">
      <%= render "bookmark", as: :question %>
      <div style="width:20px; height:20px"></div>
      <%= render "readlist", as: :question %>
      <div style="width:20px; height:20px"></div>
      <%= render "appreciation", as: :question %>
      <div style="width:20px; height:20px"></div>

      <%= form_with model: question, data: { controller: "set-private"}, local: false, html: {style: "display:flex; align-items:center"}  do |f| %>
        <label class="switch">
          <input type="checkbox" data-set-private-target="checkbox" data-action="click->set-private#switched" <%= question.is_private == 1 ? "checked" : "" %>/>
          <span class="slider round"></span>
        </label>
        <p style="margin-left:5px" data-set-private-target="text"><%= question.is_private == 1 ? "Private" : "Public" %></p>
        <%= f.hidden_field :is_private, data: { set_private_target: "field"}, id: "question_is_private"  %>
      <% end %>


    </div>
    <%= render "title", as: :question %>
    <%= render "tags", as: :question %>

    <%= render "body" %>
    
  </div> 

</div>

app/views/questions/_taglist.html.erb
<% if !@question[:tags].empty? && !@question[:tags].nil? %>
  <div style="display:flex; align-items:center; justify-content:flex-start">
    <p style="margin-right:7px; opacity:.5; font-size:.9rem"><%= !@question[:tags].nil? ? "##{@question[:tags].gsub!(", ", ", #")}" : "" %></p>
  </div>
<% end %>

app/views/questions/_tags.html.erb
<style>

</style>
<%= form_with model: @question, url: question_update_tags_path(@question), data: { controller: "select-tag"}, method: :patch, local: false do |f| %>
  <% tags = ActsAsTaggableOn::Tag.for_context(:tags).most_used(10).map { |tag| [tag.taggings_count, tag.name] } %>
  <%= f.select :tag_list, tags, {}, {multiple: true, data: {select_tag_target: "select"} } %>
  <%= f.hidden_field :tag_list, data: { select_tag_target: "input" } %>
  <%#= f.text_field :tags, data: { select_tag_target: "tags" }, value: @question.tag_list %>
<% end %>

app/views/questions/_toggle_to_bookmark.html.erb
  <%= button_to question_toggle_to_bookmark_url(@question), method: :put do %>
    <div style="display:flex; align-items:center">
      <% if current_account&.voted_for? @question, vote_scope: :bookmark %>
        <svg width="24" height="24" viewBox="0 0 32 32"><path fill="#FCD53F" d="m18.7 4.627l2.247 4.31a2.27 2.27 0 0 0 1.686 1.189l4.746.65c2.538.35 3.522 3.479 1.645 5.219l-3.25 2.999a2.225 2.225 0 0 0-.683 2.04l.793 4.398c.441 2.45-2.108 4.36-4.345 3.24l-4.536-2.25a2.282 2.282 0 0 0-2.006 0l-4.536 2.25c-2.238 1.11-4.786-.79-4.345-3.24l.793-4.399c.14-.75-.12-1.52-.682-2.04l-3.251-2.998c-1.877-1.73-.893-4.87 1.645-5.22l4.746-.65a2.23 2.23 0 0 0 1.686-1.189l2.248-4.309c1.144-2.17 4.264-2.17 5.398 0Z"/></svg>
      <% else %>
        <svg width="24" height="24" viewBox="0 0 32 32"><path fill="" d="m18.7 4.627l2.247 4.31a2.27 2.27 0 0 0 1.686 1.189l4.746.65c2.538.35 3.522 3.479 1.645 5.219l-3.25 2.999a2.225 2.225 0 0 0-.683 2.04l.793 4.398c.441 2.45-2.108 4.36-4.345 3.24l-4.536-2.25a2.282 2.282 0 0 0-2.006 0l-4.536 2.25c-2.238 1.11-4.786-.79-4.345-3.24l.793-4.399c.14-.75-.12-1.52-.682-2.04l-3.251-2.998c-1.877-1.73-.893-4.87 1.645-5.22l4.746-.65a2.23 2.23 0 0 0 1.686-1.189l2.248-4.309c1.144-2.17 4.264-2.17 5.398 0Z"/></svg>
      <% end %>
    </div>
  <% end %>

app/views/questions/_view_question.html.erb
<style>
  .view_count {
    padding:2px 6px;
    background-color:#EFEFEF;
    border-radius:7px;
    display:flex;
    align-items:center;
    color: #EFEFEF;
  }

  @media (prefers-color-scheme: light) {
    .view_count {
      color:black;
      opacity:.3;
      background-color: #EEE;
    }
  }
  @media (prefers-color-scheme: dark) {
    .view_count {
      color: #FFF;
      opacity:.4;
      background-color: transparent;
    }
  }
</style>

<div class="view_count">
  <svg width="16" height="16" viewBox="0 0 32 32"><g fill="#999"><path d="M16 22a4 4 0 1 0 0-8a4 4 0 0 0 0 8Z"/><path d="M2.484 16.237C4.3 13.367 8.674 8 16 8s11.7 5.367 13.515 8.237a3.268 3.268 0 0 1 0 3.526c-.883 1.397-2.373 3.386-4.515 5.06v4.679a.5.5 0 0 1-.728.445l-4.683-2.401A14.17 14.17 0 0 1 16 28c-7.326 0-11.7-5.367-13.516-8.237a3.267 3.267 0 0 1 0-3.526ZM23 18a7 7 0 1 0-14 0a7 7 0 0 0 14 0Z"/></g></svg>
  <div style="font-weight:bold; font-size:1rem; margin-left:2px"><%= @question.views_count %></div>
</div>

app/views/questions/edit.html.erb
<div class="container">

  <h1>Editing question</h1>

  <% content_for :title do %>
    <title><%= "Kandapedia | " + ((@question.title != "") ? @question.title : t("untitled")) %></title>
  <% end %>

  <%= render @question %>

  <br>

  <div style="margin-bottom:60px">
    <%= link_to "Show this question", @question %>  |  
    <%= link_to "Back to questions", questions_path %> |
    <%= button_to "Destroy this question", @question, method: :delete, class: "btn btn--primary" %>

  </div>

</div>

app/views/questions/index.html.erb
<div class="container">

<p style="color: green"><%= notice %></p>
  <div style="height:25px"></div>
  <h1>Questions</h1>
  <div style="height:55px"></div>
  <% @questions.desc.each do |question| %>
    <% @question = question %>
    <%= render "index_question", question: {question: @question} %>
  <% end %>
  <div style="height:50px"></div>
  <% if policy(@questions).new? and rodauth.logged_in? %>
  <%= link_to "New question", new_question_path, class: "btn btn--primary" %>
  <div style="height:90px"></div>
  <% end %>
</div>

app/views/questions/new.html.erb
<div class="container">
<h1>Nouvelle question</h1>

  <%= render "form", question: @question %>

<br>

<div>
  <%= link_to "Back to questions", questions_path %>
</div>
</div>