config/routes.rb
Rails.application.routes.draw do
  resources :candies
  resources :questions
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'

  namespace :admin do
    root to: 'home#index'
    # ... authenticated admin routes ...
    constraints Rodauth::Rails.authenticated(:admin) do
      get '/dashboard/', to: 'home#dashboard', as: 'dashboard'
    end
  end

  # ... authenticated routes ...
  constraints Rodauth::Rails.authenticated do

    resources :profiles

    post '/profiles/:id/follow', to: 'profiles#follow_profile', as: 'follow_profile'
    post '/profiles/:id/unfollow', to: 'profiles#unfollow_profile', as: 'unfollow_profile'
    post '/profiles/:id/blocking', to: 'profiles#blocking_profile', as: 'blocking_profile'
    post '/profiles/:id/unblocking', to: 'profiles#unblocking_profile', as: 'unblocking_profile'
    post '/profiles/:id/accept', to: 'profiles#accept_following', as: 'accept_following'
    post '/profiles/:id/decline', to: 'profiles#decline_following', as: 'decline_following'
    post '/profiles/:id/cancel', to: 'profiles#cancel_following', as: 'cancel_following'

    resources :questions do
      put 'add_to_readlist', to: 'questions#add_to_readlist'
      put 'remove_to_readlist', to: 'questions#remove_to_readlist'
      put 'bookmark', to: 'questions#toggle_to_bookmark'
      patch 'update_tags', to: 'questions#update_tags'

      put 'awesome_question', to: 'questions#add_awesome'
      put 'perfect_question', to: 'questions#add_perfect'
      put 'nice_question', to: 'questions#add_nice'
      put 'wrong_question', to: 'questions#add_wrong'
      put 'bad_question', to: 'questions#add_bad'
    end
    
    resources :candies do
      put 'author', to: 'candies#see_the_author'
      put 'bookmark', to: 'candies#toggle_to_bookmark'
      put 'like', to: 'candies#toggle_to_like'
      put 'boost', to: 'candies#toggle_to_boost'
      put 'view', to: 'candies#toggle_to_view'
    end
  end

end

app/models/profile.rb
# frozen_string_literal: true

class Profile < ApplicationRecord
  extend FriendlyId
  friendly_id :username, use: :slugged
  belongs_to :profileable, polymorphic: true
  has_one_attached :avatar
  before_create :add_color

  enum :is_verified, unverified: 0, verified: 1, closed: 2, checking: 3, banned: 4

  scope :verified, -> { is_verified == "verified"}
  scope :blocked, -> { is_verified == "blocked"}

  acts_as_ordered_taggable
  acts_as_ordered_taggable_on :skills
  acts_as_tagger

  validates_uniqueness_of :username, uniqueness: { case_sensitive: false }
  validates :terms_of_service, acceptance: { message: I18n.t("activerecord.errors.models.user.attributes.terms_of_service.acceptance") }

  def avatar_thumb
    avatar.variant(resize_to_limit: [100, 100]).processed
  end

  def avatar_profile
    avatar.variant(resize_to_limit: [250, 250])&.processed
  end

  def get_initial_profile
    initials = ''
    if !lastname.nil? && !firstname.nil?
      if !lastname.empty? && !firstname.empty?
        long_name = "#{lastname} #{firstname}".split(' ')
        long_name.each { |x| initials += x[0] }
        initials = username if initials.length < 2
      else
        initials = username
      end
    else
      initials = username
    end

    initials[0..2].upcase
  end

  def add_color
    self.color = Random.bytes(3).unpack1('H*').paint.brighten(23)
  end

  private

  def set_name
    @name = if (!lastname.nil? && !lastname.empty?) || (!firstname.nil? && !firstname.empty?)
              "#{lastname} #{firstname}"
            else
              username.to_s
            end
  end
end

app/controllers/profiles_controller.rb
# frozen_string_literal: true
class ProfilesController < ApplicationController
  before_action :charge_profile
  before_action -> { rodauth.require_authentication },
                only: %i[edit update follow_profile unfollow_profile blocking_profile unblocking_profile accept_following
                         cancel_following]
  before_action -> { rodauth.require_authentication },
                except: %i[show avatar_thumb charge_profile profile_params]
  after_action :set_skills, only: %i[update]

  ActsAsTaggableOn.remove_unused_tags = true
  ActsAsTaggableOn.force_lowercase = true
  # ActsAsTaggableOn.tags_table = 'skill_list'
  # ActsAsTaggableOn.taggings_table = 'skill_list'

  def pundit_user
    current_account
  end

  def follow_profile
    current_account.send_follow_request_to(@profile.profileable)
    current_account.activity_rate += 0.01
    current_account.save!
    redirect_to profiles_path(@profile)
  end

  def unfollow_profile
    make_it_an_unfriend_request

    current_account.activity_rate -= 0.01
    current_account.save!
    current_account.unfollow(@profile.profileable)
    redirect_to profiles_path(@profile)
  end

  def blocking_profile
    make_it_an_unfriend_request

    current_account.activity_rate -= 0.002
    current_account.save!
    current_account.block(@profile.profileable)
    redirect_to profiles_path(@profile)
  end

  def unblocking_profile
    make_it_an_unfriend_request

    current_account.activity_rate += 0.002
    current_account.save!
    current_account.unblock(@profile.profileable)
    redirect_to profiles_path(@profile)
  end

  def decline_following
    current_account.activity_rate += 0.002
    current_account.save!
    current_account.decline_follow_request_of(@profile.profileable)
    redirect_to root_path
  end

  def accept_following
    current_account.activity_rate += 0.01
    current_account.save!
    current_account.accept_follow_request_of(@profile.profileable)
    make_it_a_friend_request

    redirect_to root_path
  end

  def cancel_following
    current_account.activity_rate -= 0.02
    current_account.save!
    current_account.remove_follow_request_for(@profile.profileable)
    redirect_to root_path
  end

  def show
    # profile_id = @profile.id
    # @questions = Question.joins(profile: { account: :profile }).where('profiles.id = ?', profile_id)
    @questions = Question.all.where(account_id: @profile.profileable_id)
    @kandies = Candy.all.where(account_id: @profile.profileable_id)
    @profile.profileable.activity_rate -= 0.0001
    @profile.profileable.save!
    @profile = current_account.profile if @profile === nil
  end

  def edit
    authorize @profile
  end

  def update
    if @profile.update(profile_params)
      redirect_to @profile
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def avatar_thumb
    @profile.avatar.variant(resize_to_limit: [100, 100])
  end

  private

  def make_it_a_friend_request
    current_account.send_follow_request_to(@profile.profileable)
    @profile.profileable.accept_follow_request_of(current_account)
    current_account.activity_rate += 0.1
    current_account.save!
    @profile.profileable.activity_rate += 0.0005
    @profile.profileable.save!
  end

  def make_it_an_unfriend_request
    return unless @profile.profileable.mutual_following_with?(current_account)

    @profile.profileable.unfollow(current_account)
    current_account.activity_rate += 0.1
    current_account.save!
    @profile.profileable.activity_rate -= 0.001
    @profile.profileable.save!
  end

  def set_skills
    @profile[:skills] = @profile.skill_list.join ', '
    @profile.save!
  end

  def charge_profile
    if rodauth.prefix === "/user"
      @profile = Profile.friendly.where(profileable_id: params[:id], profileable_type: "Account").first
    else
      @profile = Profile.friendly.where(profileable_id: params[:id], profileable_type: "AdminAccount").first
    end

    return unless @profile.nil? && !params[:id].nil?

    @profile = Profile.friendly.find(params[:id])

  end

  def user_authenticate
    return unless rodauth.logged_in?

    @current_user = current_account
  end

  def profile_params
    params.require(:profile).permit(:username, :firstname, :lastname, :job, :bio, :terms_of_service, :avatar,
                                    :skill_list, :skills, :color)
  end
end

app/views/profiles/edit.html.erb
<style>
.text_area {
  width:100% !important;
  padding:10px 15px;
  border-radius: 7px;
}
.field input {
  width:100%;
  border-radius: 7px;
  padding:7px 10px;
}

.field {
  padding-top:20px;
}

@media (prefers-color-scheme: light) {
  .text_area {
    background-color: var(--color-white);
  }
}

@media (prefers-color-scheme: dark) {
  .text_area, .field input {
    background-color: #0a040e;
    border: 1px solid #a267f0;
    color:white
  }
  label {
    color:#a267f0;
  }
}
</style>
<div class="container">
  <%= form_for @profile, as: :profile, url: profile_path(current_account.profile), method: :patch, html: { class: "edit_profile", id: "edit_profile_#{current_account.profile.profileable_id}" } do |f| %>

    <div style="padding-bottom:var(--space-m)">
        <h4><%= @profile.profileable.email %></h4>
    </div>
    
    <div style="padding-bottom:var(--space-m)">
      <% if @profile.avatar.attached? %>
        <div style="margin-right:4px; height:100px; width:100px; border-radius:100%; display:flex; align-items:center;  justify-content: center; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">
          <%= image_tag(@profile.avatar_profile, style: "object-fit: cover; object-position: center;width:100%; height:100%; border-radius:100%", size:"100px") %>
        </div>
      <% else %>
        <div style="background-color:<%= @profile.color %>;height:100px; width:100px; border-radius:100%; display:flex; align-items:center;  justify-content: center;">
          <p style="text-align:center; font-weight:800; color:black; margin:auto; font-size:2.7rem; letter-spacing:-1px">
            <%= @profile.get_initial_profile %>
          </p>
        </div>
      <% end %>
    </div>

    <h2>Mes informations</h2>
    <div class="my-5 field">
      <%= f.file_field :avatar %>
    </div>

    <div class="my-5 field">
      <%= f.label :color %><br>
      <%= f.color_field :color, value: @profile.color, style: "height:50px; width:150px" %>
    </div>
    <div class="my-5 field">
      <%= f.label :firstname %><br>
      <%= f.text_field :firstname, value: @profile.firstname %>
    </div>
    <div class="my-5 field">
      <%= f.label :lastname %><br>
      <%= f.text_field :lastname, value: @profile.lastname %>
    </div>
    <div class="my-5 field">
      <%= f.label :job %><br>
      <%= f.text_field :job, value: @profile.job %>
    </div>

    <div class="my-5" data-controller="select-skill" style="margin:20px 0">
      <% skills = ActsAsTaggableOn::Tag.for_context(:skills).most_used(10).map { |skill| [skill.taggings_count, skill.name] } %>
      <%= f.select :skill_list, skills, {}, {multiple: true, data: {select_skill_target: "select"} } %>
      <%= f.hidden_field :skill_list, data: { select_skill_target: "input" },value: @profile.skill_list.join(", ") %>
    </div>
    <div class="my-5 field" >
      <%= f.label :bio %><br>
      <%= f.text_area :bio, value: @profile.bio, rows: "7", class: "text_area" %>
    </div>
    <div style="padding-top:var(--space-m)">
      <%= f.submit "Modifier", class: "btn btn--primary" %>
      <%= link_to "Retour", profile_path(current_account.profile), class: "btn btn--secondary" %>
    </div>

    <h2 style="margin-top:35px; margin-bottom:7px">Changer mon mot de passe</h2>
    <%= link_to "Modifier mon mot de passe", rodauth.change_password_path %>

    <div style="height:50px; width:50px; color:red;"></div>
    <%= link_to "Supprimer le compte", rodauth.close_account_path %>
    <div style="height:50px; width:50px; color:red;"></div>
  <% end %>

</div>