config/routes.rb
Rails.application.routes.draw do
  resources :candies
  resources :questions
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'

  namespace :admin do
    root to: 'home#index'
    # ... authenticated admin routes ...
    constraints Rodauth::Rails.authenticated(:admin) do
      get '/dashboard/', to: 'home#dashboard', as: 'dashboard'
    end
  end

  # ... authenticated routes ...
  constraints Rodauth::Rails.authenticated do

    resources :profiles

    post '/profiles/:id/follow', to: 'profiles#follow_profile', as: 'follow_profile'
    post '/profiles/:id/unfollow', to: 'profiles#unfollow_profile', as: 'unfollow_profile'
    post '/profiles/:id/blocking', to: 'profiles#blocking_profile', as: 'blocking_profile'
    post '/profiles/:id/unblocking', to: 'profiles#unblocking_profile', as: 'unblocking_profile'
    post '/profiles/:id/accept', to: 'profiles#accept_following', as: 'accept_following'
    post '/profiles/:id/decline', to: 'profiles#decline_following', as: 'decline_following'
    post '/profiles/:id/cancel', to: 'profiles#cancel_following', as: 'cancel_following'

    resources :questions do
      put 'add_to_readlist', to: 'questions#add_to_readlist'
      put 'remove_to_readlist', to: 'questions#remove_to_readlist'
      put 'bookmark', to: 'questions#toggle_to_bookmark'
      patch 'update_tags', to: 'questions#update_tags'

      put 'awesome_question', to: 'questions#add_awesome'
      put 'perfect_question', to: 'questions#add_perfect'
      put 'nice_question', to: 'questions#add_nice'
      put 'wrong_question', to: 'questions#add_wrong'
      put 'bad_question', to: 'questions#add_bad'
    end
    
    resources :candies do
      put 'author', to: 'candies#see_the_author'
      put 'bookmark', to: 'candies#toggle_to_bookmark'
      put 'like', to: 'candies#toggle_to_like'
      put 'boost', to: 'candies#toggle_to_boost'
      put 'view', to: 'candies#toggle_to_view'
    end
  end

end

app/views/layouts/_admin_navbar.html.erb
<header class="navbar">
  <div style="display:flex; justify-content:left; align-items:center; column-gap:1.5rem">
    <div class="navbar__brand">
      <%= link_to "Kandapedia-admin", admin_root_path, class:"--font-size-3xl navbar__brand_title", style:"font-weight: 800;font-size:2rem; font-family: 'Lily Script One', cursive; letter-spacing:-1" %>
    </div>
  </div>
  <% if rodauth(:admin).logged_in? %>

    <div class="navbar__name" data-controller="dropdown">

      <button class="navbar__name_button" data-dropdown-target="navbar__name_button" type="button" data-action="dropdown#toggle click@window->dropdown#hide">
        <div style="" class="navbar__name_avatar-box">
          <%
            if @profile != nil && current_account.id == @profile.account_id
              user = @profile
            else
              user = current_account.profile
            end
          %>
          <% if !user.nil? && user.avatar.attached? %>
            <div style="height:40px; width:40px; border-radius:100%; display:flex; align-items:center;  justify-content: center; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">
              <%= image_tag(user.avatar_profile, class: "navbar__name_image",  size:"32px") %>
            </div>
          <% else %>
            <div style="background-color:<%= user.color %>; height:35px; width:35px; border-radius:100%; display:flex; align-items:center;  justify-content: center; margin-right:5px">
              <p style="text-align:center; font-weight:800; color:black; margin:auto; font-size:.7rem; letter-spacing:-1px">
                <%= !user.nil? ? user.get_initial_profile : "---" %>
              </p>
            </div>
          <% end %>
        </div>

      </button>

      <ul data-dropdown-target="menu" class="hidden navbar__name_menu">
        <li class="account">
          <%= link_to profile_url(user) do %>
            <span class="icon user">
              <% if user.avatar.attached? %>
                <%= image_tag(user.avatar_profile, class: "navbar__name_image user",  size:"32px") %>
              <% else %>
                <div style="background-color:<%= user.color %>; height:35px; width:35px; border-radius:100%; display:flex; align-items:center;  justify-content: center; margin-right:5px">
                  <p style="text-align:center; font-weight:800; color:black; margin:auto; font-size:.7rem; letter-spacing:-1px">
                    <%= user.get_initial_profile %>
                  </p>
                </div>
              <% end %>
            </span>
            <div>
              <div class="navbar__name_name">
                <p class="navbar__name_link user">
                  <%= user.lastname != nil ? "#{user.lastname.capitalize} #{user.firstname.capitalize}" : user.username.capitalize %>
                </p>
                <span class="icons">
                  <svg xmlns="http://www.w3.org/2000/svg" width="17" height="17" viewBox="0 0 20 20"><path fill="hsl(204, 88%, 53%)" d="m8.46 1.897l.99.39a1.5 1.5 0 0 0 1.099 0l.99-.39a2.418 2.418 0 0 1 3.102 1.285l.424.975a1.5 1.5 0 0 0 .777.777l.975.424a2.418 2.418 0 0 1 1.285 3.103l-.39.99a1.5 1.5 0 0 0 0 1.098l.39.99a2.418 2.418 0 0 1-1.285 3.102l-.975.424a1.499 1.499 0 0 0-.777.777l-.424.975a2.418 2.418 0 0 1-3.103 1.285l-.99-.39a1.5 1.5 0 0 0-1.098 0l-.99.39a2.418 2.418 0 0 1-3.102-1.285l-.424-.975a1.5 1.5 0 0 0-.777-.777l-.975-.424a2.418 2.418 0 0 1-1.285-3.103l.39-.99a1.5 1.5 0 0 0 0-1.098l-.39-.99a2.418 2.418 0 0 1 1.285-3.102l.975-.424a1.5 1.5 0 0 0 .777-.777l.424-.975a2.418 2.418 0 0 1 3.103-1.285Zm4.166 5.77l-3.648 4.104l-1.625-1.625a.5.5 0 0 0-.707.707l2 2a.5.5 0 0 0 .727-.021l4-4.5a.5.5 0 0 0-.747-.665Z"/></svg>
                </span>
              </div>
              <div class="navbar__name_pseudo  user">
                @<%= user.username.downcase %>
              </div>
            </div>
          <% end %>
        </li>

        <li>
          <div class="separator"></div>
        </li>

        <li>
          <a href="#" data-action="dropdown#toggle" class="with_badge">
            <div class="title">
              <span class="icon">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="-2 -4 24 24" width="20" fill="currentColor"><path d="M9 12V1a1 1 0 1 1 2 0v11h1a1 1 0 0 1 0 2h-1v1a1 1 0 0 1-2 0v-1H8a1 1 0 0 1 0-2h1zm7-10V1a1 1 0 0 1 2 0v1h1a1 1 0 0 1 0 2h-1v11a1 1 0 0 1-2 0V4h-1a1 1 0 0 1 0-2h1zM4 5h1a1 1 0 1 1 0 2H4v8a1 1 0 0 1-2 0V7H1a1 1 0 1 1 0-2h1V1a1 1 0 1 1 2 0v4z"></path></svg>
              </span>
              <p>Paramètres</p>
            </div>
            <div class="badge">
              <p></p>
            </div>
          </a>
        </li>

        <li>
          <%= link_to rodauth(:admin).two_factor_manage_path do %>
            <span class="icon">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 16H3l3.47-4.66A2 2 0 1 0 3 9.8m7 6.2V8h4m-4 4h3m4 4v-6a2 2 0 0 1 4 0v6m-4-3h4"/></svg>
            </span>
            <p>Auth</p>
          <% end %>
        </li>

        <li>
          <%= link_to rodauth(:admin).two_factor_manage_path, data: {action: "dropdown#toggle"} do %>
            <span class="icon">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"><path fill="currentColor" d="m12 22l-.25-3h-.25q-3.55 0-6.025-2.475T3 10.5q0-3.55 2.475-6.025T11.5 2q1.775 0 3.313.662t2.7 1.825q1.162 1.163 1.824 2.7T20 10.5q0 3.8-2.275 6.813T12 22Zm-.525-6.025q.425 0 .725-.3t.3-.725q0-.425-.3-.725t-.725-.3q-.425 0-.725.3t-.3.725q0 .425.3.725t.725.3ZM11.5 12.8q.275 0 .5-.2t.3-.55q.05-.325.275-.588t.775-.812q.45-.45.75-.975t.3-1.125q0-1.275-.862-1.913T11.5 6q-.875 0-1.513.4t-1.037 1q-.175.275-.062.575t.462.425q.25.1.5 0t.45-.375q.2-.275.488-.45T11.5 7.4q.675 0 1.013.375t.337.825q0 .425-.25.763t-.6.687q-.7.6-.938.975t-.287 1.025q-.025.3.188.525t.537.225ZM14 17v1.35q1.775-1.5 2.888-3.513T18 10.5q0-2.725-1.888-4.612T11.5 4Q8.775 4 6.888 5.888T5 10.5q0 2.725 1.888 4.612T11.5 17H14Zm-2.5-5.825Z"/></svg>
            </span>
            <p>Mes questions</p>
          <% end %>
        </li>

        <li>
          <%= link_to rodauth(:admin).two_factor_manage_path, class:"with_badge", data: {action: "dropdown#toggle"} do %>
            <div class="title">
              <span class="icon">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="-3 -2 24 24" width="20" fill="currentColor"><path d="M13.666 11.782L13 11.186V6a4 4 0 1 0-8 0v5.186l-.666.596A6.987 6.987 0 0 0 2.29 15h13.42a6.987 6.987 0 0 0-2.044-3.218zM12 17a3 3 0 0 1-6 0H0a8.978 8.978 0 0 1 3-6.708V6a6 6 0 1 1 12 0v4.292A8.978 8.978 0 0 1 18 17h-6zm-3 1a1 1 0 0 0 1-1H8a1 1 0 0 0 1 1z"></path></svg>
              </span>
              <p>Notification</p>
            </div>
            <div class="badge">
              <div>
                <span class="red_badge">34</span>
              </div>
            </div>
          <% end %>
        </li>

        <li>
          <div class="separator"></div>
        </li>

        <li>
          <a href="#" data-action="dropdown#toggle">
            <span class="icon">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="-2 -2 24 24" width="20" fill="currentColor"><path d="M2 3v4h12.98l2.853-1.714a.333.333 0 0 0 0-.572L14.98 3H2zm6-2a1 1 0 1 1 2 0h4.98a2 2 0 0 1 1.03.286L18.863 3a2.333 2.333 0 0 1 0 4L16.01 8.714A2 2 0 0 1 14.98 9H10v1h7.995a2 2 0 0 1 2 2v4a2 2 0 0 1-2 2H10v1a1 1 0 0 1-2 0v-1H5.015a2 2 0 0 1-1.03-.286L1.132 16a2.333 2.333 0 0 1 0-4l2.853-1.714A2 2 0 0 1 5.015 10H8V9H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h6zm9.995 11H5.015l-2.853 1.714a.333.333 0 0 0 0 .572L5.015 16h12.98v-4z"></path></svg>
            </span>
            <p>Guides</p>
          </a>
        </li>

        <li>
          <a href="#" data-action="dropdown#toggle">
            <span class="icon">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="-5 -2 24 24" width="20" fill="currentColor"><path d="M9 14v-2.298l.856-.597a5 5 0 1 0-5.712 0l.856.597V14h1V6a1 1 0 1 1 2 0v8h1zm0 2H5v2h4v-2zM0 7a7 7 0 1 1 11 5.745V18a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-5.255A6.992 6.992 0 0 1 0 7z"></path></svg>
            </span>
            <p>Centre d'aide</p>
          </a>
        </li>

        <li>
          <a href="#" data-action="dropdown#toggle">
            <span class="icon">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="-2 -2 24 24" width="20" fill="currentColor"><path d="M6 2H3a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1V2zM3.01 8v9.965H5V13a2 2 0 0 1 2-2h2a2 2 0 0 1 2 2v4.965h6.013V8H15c-.768 0-1.47-.289-2-.764A2.989 2.989 0 0 1 11 8H9c-.768 0-1.47-.289-2-.764A2.989 2.989 0 0 1 5 8H3.01zm-2-.754A2.993 2.993 0 0 1 0 5V3a3 3 0 0 1 3-3h14a3 3 0 0 1 3 3v2c0 .882-.38 1.676-.987 2.225v10.74a2 2 0 0 1-2 2h-7.64A2.01 2.01 0 0 1 9 20H7a2.01 2.01 0 0 1-.373-.035H3.011a2 2 0 0 1-2-2V7.245zM9 17.966V13H7v4.965h2zM12 2H8v3a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1V2zm2 0v3a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1V3a1 1 0 0 0-1-1h-3zm0 9h1a1 1 0 0 1 1 1v3a1 1 0 0 1-1 1h-1a1 1 0 0 1-1-1v-3a1 1 0 0 1 1-1z"></path></svg>
            </span>
            <p>License</p>
          </a>
        </li>

        <li>
          <div class="separator"></div>
        </li>

        <li>
          <%= link_to rodauth(:admin).logout_path, data: { turbo_method: :question}, class:"logout" do %>
            <span class="icon logout">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"><path fill="currentColor" d="M12 12q-.425 0-.712-.288Q11 11.425 11 11V3q0-.425.288-.713Q11.575 2 12 2t.713.287Q13 2.575 13 3v8q0 .425-.287.712Q12.425 12 12 12Zm0 9q-1.875 0-3.512-.712q-1.638-.713-2.85-1.926q-1.213-1.212-1.926-2.85Q3 13.875 3 12q0-1.575.513-3.012Q4.025 7.55 4.95 6.4q.275-.35.7-.338q.425.013.75.338q.275.275.25.675q-.025.4-.275.75q-.65.875-1.012 1.937Q5 10.825 5 12q0 2.925 2.038 4.962Q9.075 19 12 19t4.962-2.038Q19 14.925 19 12q0-1.175-.362-2.263q-.363-1.087-1.038-1.962q-.25-.325-.275-.713q-.025-.387.25-.662q.3-.3.725-.313q.425-.012.7.313q.95 1.15 1.475 2.588Q21 10.425 21 12q0 1.875-.712 3.512q-.713 1.638-1.925 2.85q-1.213 1.213-2.85 1.926Q13.875 21 12 21Z"/></svg>
            </span>
            <p>Deconnexion</p>
          <% end %>
        </li>
      </ul>

    </div>

  <% else %>
    <%= link_to "Connexion", rodauth(:admin).login_path, class: "btn btn--primary navbar__right" %>
  <% end %>
</header>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8" />
    <title><%= @page_title ? "Kandapedia (administration) - #{@page_title}" : "Kandapedia (administration) " %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Climate+Crisis&family=DM+Serif+Text:ital@0;1&family=Inter+Tight:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Lora:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=DM+Serif+Text:ital@0;1&family=Gloock&family=Gochi+Hand&family=IBM+Plex+Sans+Hebrew:wght@300;400;500;600&family=Lily+Script+One&family=Molle&family=Nabla&family=Questrial&family=Rubik+Maze&family=Rubik+Pixels&family=Tilt+Prism&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= vite_client_tag %>
    <%= vite_javascript_tag 'application' %>
    <!--
      If using a TypeScript entrypoint file:
        vite_typescript_tag 'application'

      If using a .jsx or .tsx entrypoint, add the extension:
        vite_javascript_tag 'application.jsx'

      Visit the guide for more information: https://vite-ruby.netlify.app/guide/rails
    -->

  </head>

  <body class="body">
    <%= render "layouts/admin_navbar" %>
    <div style="width:100%; height:70px"></div>

    <!--
    <% if notice %>
      <div class="alert alert-success"><%= notice %></div>
    <% end %>
    <% if alert %>
      <div class="alert alert-danger"><%= alert %></div>
    <% end %>
    -->
  
    <%= yield %>

    <ninja-keys data-controller="command-palette" placeholder="<%= t("command_palette.placeholder") %>"></ninja-keys>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8" />
    <title><%= @page_title ? "Kandapedia - #{@page_title}" : "Kandapedia" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Climate+Crisis&family=DM+Serif+Text:ital@0;1&family=Inter+Tight:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Lora:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Dela+Gothic+One&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= vite_client_tag %>
    <%= vite_javascript_tag 'application' %>
    <!--
      If using a TypeScript entrypoint file:
        vite_typescript_tag 'application'

      If using a .jsx or .tsx entrypoint, add the extension:
        vite_javascript_tag 'application.jsx'

      Visit the guide for more information: https://vite-ruby.netlify.app/guide/rails
    -->

  </head>

  <body class="body">
    <%#= render "layouts/navbar" %>
<!--    <div style="width:100%; height:70px"></div>-->

    <!--
    <% if notice %>
      <div class="alert alert-success"><%= notice %></div>
    <% end %>
    <% if alert %>
      <div class="alert alert-danger"><%= alert %></div>
    <% end %>
    -->
  
    <%= yield %>

    <ninja-keys class="dark" style="z-index:1000" data-controller="command-palette" placeholder="<%= t("command_palette.placeholder") %>"></ninja-keys>
  </body>
</html>